force-app/main/default/objects/Active_Bot_Name__c/Active_Bot_Name__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The name of the bot in use at the moment.</description>
    <label>Active Bot Name</label>
</CustomObject>

force-app/main/default/objects/Active_Bot_Name__c/fields/Bot_Name__c.field-meta.xml
<CustomField>
    <fullName>Bot_Name__c</fullName>
    <description>The actual name value.</description>
    <label>Bot Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bot_Command__mdt/Bot_Command__mdt.object-meta.xml
<CustomObject>
    <description>The list of available bot commands.</description>
    <label>Bot Command</label>
    <pluralLabel>Bot Commands</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bot_Command__mdt/fields/Command__c.field-meta.xml
<CustomField>
    <fullName>Command__c</fullName>
    <description>The key word or command name.</description>
    <label>Command</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bot_Command__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this command active at the moment?</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bot_Prefix__mdt/Bot_Prefix__mdt.object-meta.xml
<CustomObject>
    <description>The prefix of the bot command in groups.</description>
    <label>Bot Prefix</label>
    <pluralLabel>Bot Prefixes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bot_Prefix__mdt/fields/Bot_Name__c.field-meta.xml
<CustomField>
    <fullName>Bot_Name__c</fullName>
    <description>The name of the bot; supposed to be stored in custom settings.</description>
    <label>Bot Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bot_Prefix__mdt/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <description>The actual prefix of bot&apos;s commands.</description>
    <label>Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Telegram_User__c/Telegram_User__c.object-meta.xml
<CustomObject>
    <label>Telegram User</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Telegram User Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telegram User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Telegram_User__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>User&apos;s or bot&apos;s first name.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Telegram_User__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.</description>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Telegram_User__c/fields/Is_bot__c.field-meta.xml
<CustomField>
    <fullName>Is_bot__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True, if this user is a bot.</description>
    <label>Is bot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Telegram_User__c/fields/Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Language_Code__c</fullName>
    <description>Optional. IETF language tag of the user&apos;s language.</description>
    <label>Language Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Telegram_User__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Optional. User&apos;s or bot&apos;s last name.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Telegram_User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Optional. User&apos;s or bot&apos;s username.</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/helper/VocabotWebhookHelper.cls
public with sharing class VocabotWebhookHelper {

    private static final String PROCESS_NAME = VocabotWebhookHelper.class.getName();
    private static LogHandler logger = new LogHandler();

    public static void createTelegramUser(UserWrapper user) {
        try {
            Telegram_User__c telegramUser = new Telegram_User__c();
            telegramUser.Id__c = user.id;
            telegramUser.Is_bot__c = user.is_bot;
            telegramUser.First_Name__c = user.first_name;
            telegramUser.Last_Name__c = user.last_name;
            telegramUser.Username__c = user.username;
            telegramUser.Language_Code__c = user.language_code;
            upsert telegramUser Id__c;
        } catch (Exception e) {
            logger.log(PROCESS_NAME, e.getMessage(), e.getStackTraceString());
        } finally {
            logger.save();
        }
    }

    public static Boolean shouldProceed(UpdateWrapper receivedUpdate) {
        if (receivedUpdate.message.chat.type.equals('private')) {
            return true;
        }

        Map<String, Bot_Command__mdt> commands = Bot_Command__mdt.getAll();
        String commandPostfix = Bot_Prefix__mdt.getInstance(Active_Bot_Name__c.getInstance().Bot_Name__c).Prefix__c;
        for (Bot_Command__mdt command : commands.values()) {
            if (command.Is_Active__c && receivedUpdate.message.text.startsWith(command.Command__c + commandPostfix)) {
                return true;
            }
        }
        return false;
    }
}