force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Logs errors, exceptions, messages, supports debugging.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <defaultValue>&apos;No data&apos;</defaultValue>
    <description>The description of process breakpoint.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <defaultValue>&apos;No data&apos;</defaultValue>
    <description>The process where message was logged.</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The stack trace of threw exception or error.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The timestamp of process breakpoint.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/util/LogHandler.cls
public with sharing class LogHandler {
    
    private final String DEFAULT_VALUE = Consts.BLANK_VALUE;
    
    private List<Error_Log__c> logs;
    
    public LogHandler() {
        this.logs = new List<Error_Log__c>();
    }

    public LogHandler(String processName, Object message) {
        Error_Log__c logRecord = generateLog(processName, message.toString(), DEFAULT_VALUE);
        this.logs = new List<Error_Log__c>();
        this.logs.add(logRecord);
    }

    public LogHandler(String processName, Object message, String stackTrace) {
        Error_Log__c logRecord = generateLog(processName, message.toString(), stackTrace);
        this.logs = new List<Error_Log__c>();
        this.logs.add(logRecord);
    }

    private Error_Log__c generateLog(String processName, Object message, String stackTrace) {
        Error_Log__c logRecord = new Error_Log__c();
        logRecord = new Error_Log__c();
        logRecord.Message__c = message.toString();
        logRecord.Process_Name__c = processName;
        logRecord.Stack_Trace__c = stackTrace;
        logRecord.Timestamp__c = Datetime.now();
        return logRecord;
    }

    public void log(Object message) {
        Error_Log__c logRecord = generateLog(DEFAULT_VALUE, message.toString(), DEFAULT_VALUE);
        this.logs.add(logRecord);
    }

    public void log(String processName, Object message) {
        Error_Log__c logRecord = generateLog(processName, message.toString(), DEFAULT_VALUE);
        this.logs.add(logRecord);
    }

    public void log(String processName, Object message, String stackTrace) {
        Error_Log__c logRecord = generateLog(processName, message.toString(), stackTrace);
        this.logs.add(logRecord);
    }

    public void save() {
        if (!this.logs.isEmpty()) {
            Database.insert(this.logs, false);
        }
    }
}