force-app/main/default/objects/Telegram_User__c/Telegram_User__c.object-meta.xml
<CustomObject>
    <label>Telegram User</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Telegram User Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telegram User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Telegram_User__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.</description>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/handler/VocabotWebhookHandler.cls
public without sharing class VocabotWebhookHandler {

    public static final String PROCESS_NAME = VocabotWebhookHandler.class.getName();
    private static LogHandler logger = new LogHandler();

    public VocabotWebhookHandler(UpdateWrapper receivedUpdate) {
        try {
            if (VocabotWebhookHelper.shouldProcess(receivedUpdate)) {
                logger.log(PROCESS_NAME, 'yes should');
                handleUser(receivedUpdate.message.user_from);
            } else {
                logger.log(PROCESS_NAME, 'nop');
            }
       } catch (Exception e) {
            logger.log(PROCESS_NAME, e.getMessage(), e.getStackTraceString());
       } finally {
            logger.save();
       }

    }

    private void handleUser(UserWrapper user) {
        if ([SELECT Id FROM Telegram_User__c WHERE Id__c = :user.id].isEmpty()) {
            logger.log('um : ' + [SELECT Id FROM Telegram_User__c]);
            logger.log('wth: ' + user.id);
            VocabotWebhookHelper.createTelegramUser(user);
        }
    }
}